export const FETCH_GET_ARTICLES_REQUEST = "FETCH_GET_ARTICLES_REQUEST";
export const FETCH_GET_ARTICLES_SUCCESS = "FETCH_GET_ARTICLES_SUCCESS";
export const FETCH_GET_ARTICLES_FAILURE = "FETCH_GET_ARTICLES_FAILURE";
